/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Crisp
 */
public class Fund extends javax.swing.JFrame {
int d,d1,d2,d3,d4,d5=0;
Statement smt,smt1,smt2;
ResultSet rs;
String ac,s1,s2,s3,s4,s5,s6=null;
    /**
     * Creates new form Fund
     */
    public Fund() {
     
        try {
            Connection con;
            String url = "jdbc:mysql://localhost:3306/imagepassword1";
            String driver = "com.mysql.jdbc.Driver";
            Class.forName(driver);
            con = DriverManager.getConnection(url, "root", "root");
            smt = con.createStatement();
             smt1 = con.createStatement();
             smt2 = con.createStatement();
        } catch (Exception e) {
            e.printStackTrace();
        }
      
        
        initComponents();
         Dimension scrn = getToolkit().getScreenSize();
            setBounds(0,0,scrn.width,scrn.height-30);
    }
    Fund(int a){
           this.d=a;
         System.out.println(d);
      try {
            Connection con;
            String url = "jdbc:mysql://localhost:3306/imagepassword1";
            String driver = "com.mysql.jdbc.Driver";
            Class.forName(driver);
            con = DriverManager.getConnection(url, "root", "root");
            smt = con.createStatement();
             smt1 = con.createStatement();
              smt2 = con.createStatement();
            String query = "select Accountno,iamount from atm where Cid='" + d + "'";
            rs = smt.executeQuery(query);
            while (rs.next()) {
              ac = rs.getString("Accountno");
                d1=rs.getInt("iamount");
                
                
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
         Dimension scrn = getToolkit().getScreenSize();
            setBounds(0,0,scrn.width,scrn.height-30);
            s1=Integer.toString(d1);
            System.out.println(s1);
            jTextField2.setText(s1);
            jTextField3.setText(ac);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("FUND TRANSCATION");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(450, 20, 200, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1090, 0);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("FUND TRANSACTION");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(490, 30, 210, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1090, 90);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("TransferAmount:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(200, 80, 130, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("AvailableAmount:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(660, 80, 110, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("AccountNumber(From):");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(170, 280, 160, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("AccountNumber(To):");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(650, 290, 130, 30);
        jPanel3.add(jTextField1);
        jTextField1.setBounds(320, 70, 260, 40);
        jPanel3.add(jTextField2);
        jTextField2.setBounds(770, 70, 260, 40);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField3);
        jTextField3.setBounds(330, 280, 260, 40);
        jPanel3.add(jTextField4);
        jTextField4.setBounds(790, 280, 260, 40);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Transfer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(490, 400, 120, 40);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(680, 400, 120, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 90, 1090, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
    	int ta=0,aa=0,am=0;
			
			//JOptionPane.showMessageDialog(this,"sdfs");
			s1=jTextField1.getText();
			s2=jTextField2.getText();
			s3=jTextField3.getText();
			s4=jTextField4.getText();
			if((jTextField1.getText().equals(""))||(jTextField2.getText().equals(""))||(jTextField3.getText().equals(""))||(jTextField4.getText().equals(""))){
				JOptionPane.showMessageDialog(this,"Some Values Missing");
			}
			//else if(ta>aa){
				//JOptionPane.showMessageDialog(this,"Amount Limit is Invalid");
			//}
			else{
				ta=Integer.parseInt(s1);
				aa=Integer.parseInt(s2);
				am=aa-ta;
				
				if(ta>aa){
					JOptionPane.showMessageDialog(this,"Amount Limit is Invalid");
				}
				else{
				try{
					int k=0;
					//st=con.createStatement();
					
					String query="select iamount from atm where Accountno='"+s4+"'";
					//JOptionPane.showMessageDialog(this,query);
					rs=smt.executeQuery(query);
					if(rs.next()){
						//JOptionPane.showMessageDialog(this,"111111");
						int add=rs.getInt(1);
						System.out.println(add);
						add=add+ta;
						System.out.println(add);
						
						//System.out.println("After tran");
						String q1="update atm set iamount='"+add+"'where Accountno='"+s4+"'";
						k=smt1.executeUpdate(q1);
					
					}
					
					String que="select iamount from atm where Accountno='"+s3+"'";
					rs=smt.executeQuery(que);
					if(k==1){
					if(rs.next()){
						int sub=rs.getInt(1);
						sub=sub-ta;
						
						String q2="update atm set iamount='"+sub+"'where Accountno='"+s3+"'";
						smt2.executeUpdate(q2);
					}
					JOptionPane.showMessageDialog(this,"Sucessfully Transferd");
					int op=JOptionPane.showConfirmDialog(this,"Whould you like to continue?");
					
					}
				}
				catch(Exception e){
					JOptionPane.showMessageDialog(this,"Some Error in fields");
					e.printStackTrace();
				}
				}
			}
}   catch(Exception e){
    e.printStackTrace();
}    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      this.hide();
   Pinno  l=new Pinno();
      l.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fund().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
