/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Crisp
 */
public class Pinno extends javax.swing.JFrame {
 Statement smt;
 int c,id,a=0;
    /**
     * Creates new form Pinno
     */
    public Pinno() {
        try{
            Connection con;
            String url = "jdbc:mysql://localhost:3306/imagepassword1";
            String driver = "com.mysql.jdbc.Driver";
            Class.forName(driver);
            con = DriverManager.getConnection(url, "root", "root");
            smt = (Statement) con.createStatement();
           // String s100=jPasswordField1.getText();
            //System.out.println(s100);
        }catch(Exception e){
            e.printStackTrace();
        }
        initComponents();
    }

//    Pinno(int s) {
//      try{
//            Connection con;
//            String url = "jdbc:mysql://localhost:3306/imagepassword1";
//            String driver = "com.mysql.jdbc.Driver";
//            Class.forName(driver);
//            con = DriverManager.getConnection(url, "root", "root");
//            smt = (Statement) con.createStatement();
//            
//        }catch(Exception e){
//            e.printStackTrace();
//        }
//      this.a=s;
//      System.out.println(a);
//        initComponents();
//    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 550));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("ATM APPLICATION");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 30, 190, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 80);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Enter An OTP No");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(60, 140, 140, 40);
        jPanel2.add(jPasswordField1);
        jPasswordField1.setBounds(200, 140, 240, 40);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText(" Continue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(280, 230, 110, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 80, 600, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
           String s=jPasswordField1.getText();
           System.out.println(s);
           ResultSet rs=smt.executeQuery("select id,pinnumber from register where pinnumber='"+s+"' ");
  if(rs.next()){
      id=rs.getInt("id");
      
      c=rs.getInt("pinnumber");
      System.out.println(id+c+"hai java");
       
   }
   String d=Integer.toString(c);
   if(s.equalsIgnoreCase(d)){
       JOptionPane.showMessageDialog(this, "PinNumber Is Correct");
       
       ATM l1=new ATM(id);
       l1.setVisible(true);
       this.hide();
   }else{
        JOptionPane.showMessageDialog(this, "PinNumber Is InCorrect");
   }
       }catch(Exception e){
           e.printStackTrace();
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pinno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pinno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pinno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pinno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pinno().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
