
import java.awt.Color;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Suresh A
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    String a;
    Statement smt;

    public Register() {
        try {
            Connection con;
            String url = "jdbc:mysql://localhost:3306/imagepassword1";
            String driver = "com.mysql.jdbc.Driver";
            Class.forName(driver);
            con = DriverManager.getConnection(url, "root", "root");
            smt = con.createStatement();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        initComponents();
      
  
//        Dimension scrn = getToolkit().getScreenSize();
//        setBounds(0, 0, scrn.width, scrn.height - 30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 850));
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText(" User Name:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(240, 20, 110, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Password:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(260, 80, 100, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText(" Confirm Password:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(200, 140, 170, 20);

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(400, 10, 210, 40);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(390, 490, 230, 50);

        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        jPanel2.add(jPasswordField1);
        jPasswordField1.setBounds(400, 70, 210, 40);

        jPasswordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusLost(evt);
            }
        });
        jPanel2.add(jPasswordField2);
        jPasswordField2.setBounds(400, 130, 210, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Secret Question:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(210, 220, 150, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "What is your pet name?", "What is your favorite team?", "What is your favorite movie?", "What is your favorite color?", "What was the name of your first startup?" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(400, 200, 210, 50);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Answer:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(240, 280, 120, 40);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(400, 280, 210, 40);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Phone Number:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(220, 350, 150, 30);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jPanel2.add(jTextField3);
        jTextField3.setBounds(400, 340, 210, 40);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Mail-Id:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(250, 400, 120, 21);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });
        jPanel2.add(jTextField4);
        jTextField4.setBounds(400, 400, 210, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 50, 930, 640);

        jLabel6.setText(" ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 480, 1000, 230);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText(" REGISTER NOW");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 10, 230, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Random ramgen = new Random();

            int random = ramgen.nextInt(100);
            String b = (String) jComboBox1.getSelectedItem();
            System.out.println(b);
            if ((jTextField1.getText().length() != 0) && (jTextField2.getText().length() != 0) && (jTextField3.getText().length() != 0) && (jTextField4.getText().length() != 0) && (jPasswordField1.getText().length() != 0)) {
                if(jPasswordField1.getText().equals(jPasswordField2.getText()))
                {
                    
                    ResultSet rs=smt.executeQuery("select * from register where username='"+ jTextField1.getText() +"'");
                     if(rs.next()) {
                         
                JOptionPane.showMessageDialog(this, "Username already exist!!!");
             
                this.setVisible(false);
                    new  Welcomepage();
                     }   else{
                              String insertQuery = "insert into register values('" + random + "','" + jTextField1.getText() + "','" + jPasswordField1.getText() + "','" + jPasswordField2.getText() + "','" + b + "','" + jTextField2.getText() + "','" + jTextField3.getText() + "','" + jTextField4.getText() + "','" + 0 + "','" + 1 + "','" + 2 + "','" + 3 + "','" + 4 + "','" + 4 + "')";
                smt.executeUpdate(insertQuery);

                int a = random;

                JOptionPane.showMessageDialog(this, "Added Successfully!!!");
                JOptionPane.showMessageDialog(this, "Please Enter More Fields!!!");
                this.setVisible(false);
                new test(a);
                     }   
                //String insertQuery = "insert into register values('" + random + "','" + jTextField1.getText() + "','" + jPasswordField1.getText() + "','" + jPasswordField2.getText() + "','" + 1 + "','" + 2 + "','" + 3 + "')";
           
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Password was Mismatch");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Regitser Failed");
            }


        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        try {
            if (jTextField1.getText().length() != 0) {
                jPasswordField1.setVisible(true);
                jPasswordField2.setVisible(true);
                jComboBox1.setVisible(true);
                jTextField2.setVisible(true);
                jTextField3.setVisible(true);
                jTextField4.setVisible(true);

            } else {
                jPasswordField1.setVisible(false);
                jPasswordField2.setVisible(false);
                jComboBox1.setVisible(false);
                jTextField2.setVisible(false);
                jTextField3.setVisible(false);
                jTextField4.setVisible(false);


                JOptionPane.showMessageDialog(null, "Eneter the username");

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        try {
            if (jPasswordField1.getText().length() != 0) {

                jPasswordField2.setVisible(true);
                jComboBox1.setVisible(true);
                jTextField2.setVisible(true);
                jTextField3.setVisible(true);
                jTextField4.setVisible(true);

            } else {

                jPasswordField2.setVisible(false);
                jComboBox1.setVisible(false);
                jTextField2.setVisible(false);
                jTextField3.setVisible(false);
                jTextField4.setVisible(false);


                JOptionPane.showMessageDialog(null, "Eneter the Password");

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jPasswordField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusLost
        try {
            if (jPasswordField2.getText().length() != 0) {


                jComboBox1.setVisible(true);
                jTextField2.setVisible(true);
                jTextField3.setVisible(true);
                jTextField4.setVisible(true);

            } else {


                jComboBox1.setVisible(false);
                jTextField2.setVisible(false);
                jTextField3.setVisible(false);
                jTextField4.setVisible(false);


                JOptionPane.showMessageDialog(null, "Eneter the Conform Password");

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jPasswordField2FocusLost

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        try {
            if (jTextField2.getText().length() != 0) {




                jTextField3.setVisible(true);
                jTextField4.setVisible(true);

            } else {



                jTextField3.setVisible(false);
                jTextField4.setVisible(false);


                JOptionPane.showMessageDialog(null, "Eneter the Answer");

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        try {

            String str_phone_no = jTextField3.getText();
            Pattern p = Pattern.compile("^\\(?(\\d{3})\\)?[- ]?(\\d{3})[- ]?(\\d{4})$");
            Matcher m = p.matcher(str_phone_no);
            boolean matchFound = m.matches();
            if (jTextField3.getText().length() != 0) {
                if (matchFound) {
                    jTextField4.setVisible(true);
                    JOptionPane.showMessageDialog(this, "Phone number format is ok.");
                    System.out.println("Phone number format is ok.");
                } else {
                    jTextField4.setVisible(false);
                    JOptionPane.showMessageDialog(this, "Wrong phone number format.");
                    System.out.println("Wrong phone number format.");
                }
            } else {




                jTextField4.setVisible(false);


                JOptionPane.showMessageDialog(null, "Eneter the Phone Number");

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        try {
//            if (jTextField4.getText().length() != 0) {
//                String email = jTextField4.getText();
//                Pattern p = Pattern.compile("[a-zA-Z]*[0-9]*@[a-zA-Z]*.[a-zA-Z]*");
//                Matcher m = p.matcher(email);
////Matcher m=p.matcher(args[0]);
//                boolean b = m.matches();
//                if (b == true) {
//                    System.out.println("Valid Email ID");
//                    JOptionPane.showMessageDialog(null, "Valid Email ID");
//                }
//            } else {
//                System.out.println("InValid Email ID");
//                JOptionPane.showMessageDialog(null, "InValid Email ID");
//            }
            String email =  jTextField4.getText();;

      //Set the email pattern string
      Pattern p = Pattern.compile(".+@.+\\.[a-z]+");

      //Match the given string with the pattern
      Matcher m = p.matcher(email);

      //check whether match is found 
      boolean matchFound = m.matches();

      if (matchFound){
        System.out.println("Valid Email Id.");
      JOptionPane.showMessageDialog(null, "Valid Email ID");
      }else{
        System.out.println("Invalid Email Id.");
       JOptionPane.showMessageDialog(null, "InValid Email ID");
      }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTextField4FocusLost

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusGained
    
    }//GEN-LAST:event_jTextField4FocusGained

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
      
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
