
import java.awt.Dimension;
import java.io.IOException;
import java.net.URL;
import java.net.URLConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JEditorPane;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Suresh A
 */
public class slider extends javax.swing.JFrame {
int g=0;
Statement smt;
String uname=null;
String pass=null;
String image1=null;
String image2=null;
String slider=null;
String phone=null;
String mail,pinnumber=null;
 static final String _userName = "9345031930";
  static final String _password = "12251992";
  static final String _url = "http://ubaid.tk/sms/sms.aspx";
    static final String charset = "UTF-8";
   public slider(int f) {
         try {
            Connection con;
            String url = "jdbc:mysql://localhost:3306/imagepassword1";
            String driver = "com.mysql.jdbc.Driver";
            Class.forName(driver);
            con = DriverManager.getConnection(url, "root", "root");
            smt = con.createStatement();
        } catch (Exception e) {
            e.printStackTrace();
        }
         
        initComponents();
        this.g=f;
        System.out.println("g"+g);
//         Dimension scrn = getToolkit().getScreenSize();
//            setBounds(0,0,scrn.width,scrn.height-30);
    }

     slider() {
          try {
            Connection con;
            String url = "jdbc:mysql://localhost:3306/imagepassword1";
            String driver = "com.mysql.jdbc.Driver";
            Class.forName(driver);
            con = DriverManager.getConnection(url, "root", "root");
            smt = con.createStatement();
        } catch (Exception e) {
            e.printStackTrace();
        }
         
        initComponents();
//        this.g=f;
//        System.out.println("g"+g);
//         Dimension scrn = getToolkit().getScreenSize();
//            setBounds(0,0,scrn.width,scrn.height-30);
        
    }

    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 750));
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jSlider1.setMaximum(1000);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jSlider1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jSlider1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(jSlider1);
        jSlider1.setBounds(120, 70, 860, 80);

        jTextField1.setText(" ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(320, 210, 200, 40);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText(" Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(550, 200, 150, 60);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText(" Select the Count:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(160, 210, 150, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 90, 1140, 340);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("REGISTER");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(500, 20, 140, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1140, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jSlider1AncestorAdded
//      int value = jSlider1.getValue();
//  String str = Integer.toString(value);
//  jTextField1.setText(str);
    }//GEN-LAST:event_jSlider1AncestorAdded

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
       
            int value = jSlider1.getValue();
       String str = Integer.toString(value);
       jTextField1.setText(str);
                           
          
       
         
    }//GEN-LAST:event_jSlider1StateChanged

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       jTextField1.setVisible(false);
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int query=0,random=0;
            Random ramgen = new Random();

            random = ramgen.nextInt(1000);
            
           
                   query=smt.executeUpdate("update register set  slidercount='"+jTextField1.getText()+"',pinnumber='"+random+"'where id='"+g+"'");
                  if(query==1){
                  JOptionPane.showMessageDialog(this, "Register Successfully!!! Pin number   "+random);
//                  msg();
               //  mail();
//               SmsSender s=   new SmsSender(g);
//                 
//               
//                    String testPhoneNo ="9876543210";
//        String testMessage = "Sending Messages From java is not too hard";
//            s.sendMessage(testPhoneNo,testMessage);
//                   NewGrid n=new NewGrid(g);
//                   n.setVisible(true);
                   
                 Welcomepage ad=new Welcomepage();
                  ad.setVisible(true);
                  this.hide();
                  }
        } catch (Exception ex) {
            ex.printStackTrace();
        } 
        

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(slider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(slider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(slider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(slider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
           

            @Override
            public void run() {
              new slider().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
//public void msg(){
//   
//    try{
//   ResultSet rs=smt.executeQuery("select username,password,phoneno,mailid,imagepixelx,imagepixely,pinnumber,slidercount from register where id='"+g+"' ");
//   while(rs.next()){
//       uname=rs.getString("username");
//       pass=rs.getString("password");
//       phone=rs.getString("phoneno");
//       mail=rs.getString("mailid");
//       image1=rs.getString("imagepixelx");
////    //String url = "http://ubaid.tk/sms/sms.aspx?uid=9345031930&pwd=12251992&msg="+"ver"+"&phone=97
//       image2=rs.getString("imagepixely");
//       pinnumber=rs.getString("pinnumber");
//       slider=rs.getString("slidercount");
//       
//   }
//   
////   String msg="You Have Loged On To Your Account";
////                  String url = "http://ubaid.tk/sms/sms.aspx?uid=9786676521&pwd=254144&msg="+"Message:"+msg+"UserName:"+uname+"Password:"+pass+"ImagePixelX:"+image1+"ImagePixelY:"+image2+"SliderCount:"+slider+"&phone="+phone+"&provider=way2sms";  
////    51276580&provider=smsfi";  
////   
////    
////    //* way to send sms 2 *////
////    JEditorPane editorPane = new JEditorPane(url);
////    editorPane.setEditable(false);
//////  URL url1 = new URL(url);
//////URLConnection con = url1.openConnection();
//   
//   
//    }catch(Exception e){
//        e.printStackTrace();
//    }
//    
//}
public void mail(){
      final String username = "karpalagar@gmail.com";
        final String password = "aguz yqyh xskg eytv"; // update here

		Properties prop = new Properties();
		prop.put("mail.smtp.host", "smtp.gmail.com");
        prop.put("mail.smtp.port", "465");
        prop.put("mail.smtp.auth", "true");
        prop.put("mail.smtp.socketFactory.port", "465");
        prop.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        
        Session session = Session.getInstance(prop,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(username, password);
                    }
                });

 
		try {
                          String msg="You Have Loged On To Your Account";
			Message message = new MimeMessage(session);
			message.setFrom(new InternetAddress("karpalagar@gmail.com"));
			message.setRecipients(Message.RecipientType.TO,
				InternetAddress.parse(mail));
			message.setSubject("Testing Subject");
			message.setText("Message:"+msg+"UserName:"+uname+"Password:"+pass+"ImagePixelX:"+image1+"ImagePixelY:"+image2+"pinnumber:"+pinnumber+"SliderCount:"+slider);
 
			Transport.send(message);
 
			System.out.println("Done");
 
		} catch (MessagingException e) {
			throw new RuntimeException(e);
		}
}

}
