
import java.awt.Dimension;
import java.sql.*;
import java.util.Properties;
import java.util.Random;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import org.sms.service.api.SMS;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Suresh A
 */
public class slider_1 extends javax.swing.JFrame {
String g=null;
int c=0;
int d=0;
String count=null;
Statement smt,smt1;
 ResultSet rs = null;
 String s3=null;
 
 String s6=null;
 int r=0;
 int t=0;
 String e=null;
 String f=null;
 int  h=0;
 int s=0;
 String uname=null;
String pass=null;
String image1=null;
String image2=null;
String slider=null;
String phone=null;
String mail=null;
   int random=0;
 int s4,s5, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16 = 0;
   public slider_1(String f,int a,int b) {
         try {
            Connection con;
            String url = "jdbc:mysql://localhost:3306/imagepassword1";
            String driver = "com.mysql.jdbc.Driver";
            Class.forName(driver);
            con = DriverManager.getConnection(url, "root", "root");
            smt = con.createStatement();
             smt1 = con.createStatement();
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
        this.g=f;
        this.c=a;
        this.d=b;
        System.out.println("g:"+g);
        System.out.println("X:"+a);
        System.out.println("Y:"+b);
        System.out.println("X:"+c);
        System.out.println("Y:"+d);
        
    }

    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 750));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("REGISTER");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(390, 20, 140, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1140, 90);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jSlider1.setMaximum(1000);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jSlider1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jSlider1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(jSlider1);
        jSlider1.setBounds(40, 40, 860, 80);

        jTextField1.setText(" ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(320, 150, 200, 40);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText(" Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(560, 140, 150, 60);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText(" Select the Count:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(170, 150, 120, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 90, 1140, 220);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("REGISTER");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(500, 20, 140, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jSlider1AncestorAdded
//      int value = jSlider1.getValue();
//  String str = Integer.toString(value);
//  jTextField1.setText(str);
    }//GEN-LAST:event_jSlider1AncestorAdded

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
       
            int value = jSlider1.getValue();
       String str = Integer.toString(value);
       jTextField1.setText(str);
                           
          
       
         
    }//GEN-LAST:event_jSlider1StateChanged

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       jTextField1.setVisible(false);
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            count=jTextField1.getText();
            String query ="select * from register where password='"+ g +"'";
                rs =smt.executeQuery(query);
                while (rs.next()) {
                     s16=rs.getInt("id");
                 s3 = rs.getString("username");
                   mail=rs.getString("mailid");
                  s4 = rs.getInt("imagepixelx");
                     s5 = rs.getInt("imagepixely");
                  s6=rs.getString("slidercount");
                  
                    //s5=rs.getString(7);
                    System.out.println(s3);
                    System.out.println(s4);
                }
                
                r=s4+5;
                  t=s4-5;
                  h=s5+5;
                  s=s5-5;
                   System.out.println("+5 inc:"+c);
                  System.out.println("+5 inc:"+r);
                    System.out.println("-5:"+t);
                    System.out.println("+5:"+h);
                    System.out.println("-5:"+s);
//                  e=Integer.toString(c);
//                  f=Integer.toString(d);
                  if(((r<=c)||(t<=c))&&((h<=d)||(s<=d))&& ((count.equalsIgnoreCase(s6)))){
                      

                      JOptionPane.showMessageDialog(this, "Login Successfully!!!");
                        Random ramgen = new Random();

         random = ramgen.nextInt(10000);
            
             int query1,z=0;
                  query1=smt.executeUpdate("update register set  pinnumber='"+random+"' where username='"+s3+"'");
                   z=smt1.executeUpdate("update atm set  pinno='"+random+"' where name='"+s3+"'");
                  JOptionPane.showMessageDialog(this,"Your Recent Pin is "+random);
                  msg();
              ///  mail();

             System.out.println(s16+s6);
                Pinno no=new Pinno();
                no.setVisible(true);        
                this.hide();
                  }else {
                       JOptionPane.showMessageDialog(this, "Access Dined !!!");
                  }
                      //x++;
                 
        }catch(Exception e){
            e.printStackTrace();
        }
            

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(slider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(slider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(slider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(slider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
           

            @Override
            public void run() {
               // new slider().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
public void msg(){
   
    try{
   ResultSet rs=smt.executeQuery("select * from register where password='"+ g +"'");
   while(rs.next()){
      uname=rs.getString("username");
       pass=rs.getString("password");
       phone=rs.getString("phoneno");

                s14 = rs.getInt("pinnumber");
       slider=rs.getString("slidercount");
       SMS s=new SMS();
        s.SendSMS(phone,"Updated pin number is: "+s14);
       
       
   }
   

   
    }catch(Exception e){
        e.printStackTrace();
    }
    
}
public void mail(){
     final String username = "karpalagar@gmail.com";
        final String password = "aguz yqyh xskg eytv"; // update here

		Properties prop = new Properties();
		prop.put("mail.smtp.host", "smtp.gmail.com");
        prop.put("mail.smtp.port", "465");
        prop.put("mail.smtp.auth", "true");
        prop.put("mail.smtp.socketFactory.port", "465");
        prop.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        
        Session session = Session.getInstance(prop,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(username, password);
                    }
                });

                    
		try {
                          String msg="You Have Loged On To Your Account";
			Message message = new MimeMessage(session);
			message.setFrom(new InternetAddress("asvperumal@gmail.com"));
			message.setRecipients(Message.RecipientType.TO,
				InternetAddress.parse(mail));
			message.setSubject("Testing Subject");
			//message.setText("Message:"+msg+"UserName:"+uname+"Password:"+pass+"ImagePixelX:"+image1+"ImagePixelY:"+image2+"ImagePixelX:"+s7+"ImagePixelY:"+s8+"ImagePixelX:"+s9+"ImagePixelY:"+s10+"ImagePixelX:"+s11+"ImagePixelY:"+s12+"ImagePixelX:"+s13+"ImagePixelY:"+s14+"SliderCount:"+slider);
                        message.setText("Message:"+msg+"PinNumber:"+s14);
 
			Transport.send(message);
 
			System.out.println("Done");
 
		} catch (MessagingException e) {
			throw new RuntimeException(e);
		}
}
}
