
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Suresh A
 */
public class Welcomepage extends javax.swing.JFrame {
Statement smt;
String user,pass,usern,passw=null;
ResultSet rs;
    /**
     * Creates new form Welcomepage
     */
    public Welcomepage() {
        try {
            Connection con;
            String url = "jdbc:mysql://localhost:3306/imagepassword1";
            String driver = "com.mysql.jdbc.Driver";
            Class.forName(driver);
            con = DriverManager.getConnection(url, "root", "root");
            smt = con.createStatement();
        } catch (Exception e) {
            e.printStackTrace();
        }
        try{
         UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
        }catch(Exception e){
            e.printStackTrace();
        }
        initComponents();
        
//        Dimension scrn = getToolkit().getScreenSize();
//            setBounds(0,0,scrn.width,scrn.height-30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(950, 750));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1050, 0);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_hdfcbank.gif"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 50, 220, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about-cb.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 210, 640, 510);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Username:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 10, 80, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Password:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 60, 80, 40);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(50, 100, 80, 30);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(110, 20, 170, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("New User Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(130, 100, 150, 30);
        jPanel2.add(jPasswordField1);
        jPasswordField1.setBounds(110, 60, 170, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(630, 200, 400, 140);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/article-new-ehow-images-a05-u7-cd-log-bank-america_s-online-banking-800x800.jpg"))); // NOI18N
        jLabel5.setText(" ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 420, 220);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/banner_949.jpg"))); // NOI18N
        jLabel6.setText(" ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(420, 0, 610, 190);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/article-new-ehow-images-a08-5n-3g-factors-responsible-growth-internet-banking-800x800.jpg"))); // NOI18N
        jLabel7.setText(" ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(630, 340, 400, 270);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/indian banking system.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(630, 610, 400, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.setVisible(false);
        Register reg=new Register();
       reg.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
          user=jTextField1.getText();
          pass=jPasswordField1.getText();
        int i=0;
            String query = "select username,password from register where username='"+user+"'  ";
            rs = smt.executeQuery(query);
            if (rs.next()) {
                usern=rs.getString("username");
                passw=rs.getString("password");
                 if((user.equalsIgnoreCase(usern))&&(pass.equalsIgnoreCase(passw))){
                     i=1;
                 }
            }
            if(i==1){
           
                
                
                    JOptionPane.showMessageDialog(this,"Valid User");
                    this.setVisible(false);
        String a=pass;
       Pinno1 n=new Pinno1(a);
        n.setVisible(true);
        this.hide();
//        Pinno1 p=new Pinno1(a);
//        p.setVisible(true);
//       new test_1(a);
                }else if((user.equalsIgnoreCase("admin"))&&(pass.equalsIgnoreCase("admin"))){
                    adminviewform ad=new adminviewform();
                    ad.setVisible(true);
                    this.hide();
                }
       else{
                    JOptionPane.showMessageDialog(this,"Please Enter Valid Id and Name");
                }
      }catch(Exception e){
          e.printStackTrace();
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**try{
          user=jTextField1.getText();
          pass=jPasswordField1.getText();
        int i=0;
            String query = "select username,password from register where username='"+user+"'  ";
            rs = smt.executeQuery(query);
            if (rs.next()) {
                usern=rs.getString("username");
                passw=rs.getString("password");
                 if((user.equalsIgnoreCase(usern))&&(pass.equalsIgnoreCase(passw))){
                     i=1;
                 }
            }
            if(i==1){
           
                
                
                    JOptionPane.showMessageDialog(this,"Valid User");
                    this.setVisible(false);
        String a=pass;
        NewGrid1 n=new NewGrid1(a);
        n.setVisible(true);
        this.hide();
//        Pinno1 p=new Pinno1(a);
//        p.setVisible(true);
//       new test_1(a);
                }else if((user.equalsIgnoreCase("admin"))&&(pass.equalsIgnoreCase("admin"))){
                    adminviewform ad=new adminviewform();
                    ad.setVisible(true);
                }
       else{
                    JOptionPane.showMessageDialog(this,"Please Enter Valid Id and Name");
                }
      }catch(Exception e){
          e.printStackTrace();
      }
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try
        {
            UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
        }catch(Exception e)
        {
            e.printStackTrace();
        }
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
         java.awt.EventQueue.invokeLater(new Runnable(){

            public void run() {
                new Welcomepage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
