/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Crisp
 */
public class With extends javax.swing.JFrame {
int d,d1,d2,d3,d4,d5=0;
Statement smt,smt1,smt2;
ResultSet rs;
String s1,s2,s3,s4,s5,s6=null;
    /**
     * Creates new form With
     */
    public With() {
        try {
            Connection con;
            String url = "jdbc:mysql://localhost:3306/imagepassword";
            String driver = "com.mysql.jdbc.Driver";
            Class.forName(driver);
            con = DriverManager.getConnection(url, "root", "root");
            smt = con.createStatement();
             smt1 = con.createStatement();
             smt2 = con.createStatement();
        } catch (Exception e) {
            e.printStackTrace();
        }
   
        initComponents();
         Dimension scrn = getToolkit().getScreenSize();
            setBounds(0,0,scrn.width,scrn.height-30);
    }
    With(int a){
         this.d=a;
         System.out.println(d);
      try {
            Connection con;
            String url = "jdbc:mysql://localhost:3306/imagepassword1";
            String driver = "com.mysql.jdbc.Driver";
            Class.forName(driver);
            con = DriverManager.getConnection(url, "root", "root");
            smt = con.createStatement();
             smt1 = con.createStatement();
              smt2 = con.createStatement();
            String query = "select Cid,name,emailid,Accountno,Cardno,pinno,iamount from atm where Cid='" + d + "'";
            rs = smt.executeQuery(query);
            while (rs.next()) {
                d3 = rs.getInt("Cid");
                s2 = rs.getString("name");
                s3 = rs.getString("emailid");
                d2 = rs.getInt("Accountno");
                d4 = rs.getInt("Cardno");
                d5 = rs.getInt("pinno");
                d1 = rs.getInt("iamount");

            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
         Dimension scrn = getToolkit().getScreenSize();
            setBounds(0,0,scrn.width,scrn.height-30);
            s1=Integer.toString(d1);
            System.out.println(s1);
            jTextField2.setText(s1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("WITHDRAW");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(510, 30, 170, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1060, 100);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Amount:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(350, 120, 90, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Available Amount:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(320, 220, 130, 20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(460, 110, 260, 50);

        jTextField2.setText(" ");
        jPanel2.add(jTextField2);
        jTextField2.setBounds(460, 210, 260, 50);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText(" Withdraw");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(380, 330, 139, 50);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(570, 330, 120, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 100, 1060, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      this.hide();
     Pinno l=new Pinno();
      l.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try{
          
			if(jTextField1.getText().equals("")){
				JOptionPane.showMessageDialog(this,"Enter a amount");
			}
			else{
				int a=Integer.parseInt(jTextField1.getText());
				int ta=Integer.parseInt(jTextField2.getText());
				if(a>ta){
					JOptionPane.showMessageDialog(this,"Amount is greater than current amount");
				}
				else{
					
				try{
					
					
					String query="select iamount from atm where Accountno='"+d2+"'";
					rs=smt.executeQuery(query);
					if(rs.next()){
						int add=rs.getInt(1);
						//System.out.println(add);
						add=add-a;
						//System.out.println(add);
						
						
						String q1="update atm set iamount='"+add+"'where Accountno='"+d2+"'";
						smt1.executeUpdate(q1);
                                                String quer = "insert into allcustomer values('" + d3 + "','" + s2 + "','" + d2 + "','" +d1+ "','" + a + "')";
                        smt2.executeUpdate(quer);
					}
					JOptionPane.showMessageDialog(this,"Amount is creasted");
					int op=JOptionPane.showConfirmDialog(this,"Whould you like to continue?");
					
				}
				catch (Exception e) {
					e.printStackTrace();
				}
                                }
				
      }
                            }catch(Exception e){
                                e.printStackTrace();
                            }
         


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(With.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(With.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(With.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(With.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new With().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
